
import java.awt.Color;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xmach
 */
public class diathesimotita extends javax.swing.JFrame {

    /**
     * Creates new form diathesimotita
     */
    public diathesimotita() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable14 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jTabbedPane3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));

        jTable1.setBackground(new java.awt.Color(102, 0, 0));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(225, 225, 225));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Absolut",  new Integer(35)},
                {"Absolut Citron",  new Integer(65)},
                {"Absolut Elyx",  new Integer(34)},
                {"Absolut Vanilia",  new Integer(24)},
                {"Baltic Crystal",  new Integer(15)},
                {"Belvedere Pure",  new Integer(86)},
                {"Ciroc",  new Integer(39)},
                {"elit Ultra Luxury Vodka",  new Integer(28)},
                {"Finlandia",  new Integer(24)},
                {"Green Mark",  new Integer(19)},
                {"Grey Goose VX",  new Integer(34)},
                {"Haku Vodka",  new Integer(16)},
                {"Kauffman Soft",  new Integer(35)},
                {"Russian Standard",  new Integer(26)},
                {"Russian Standard Gold",  new Integer(38)},
                {"Serkova",  new Integer(12)}
            },
            new String [] {
                "Βότκα", "Απόθεμα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAlignmentX(1.5F);
        jTable1.setAlignmentY(1.5F);
        jTable1.setGridColor(new java.awt.Color(225, 225, 225));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable1.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 259, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Βότκα", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setBackground(new java.awt.Color(102, 0, 0));
        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable2.setForeground(new java.awt.Color(225, 225, 225));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Beefeater 24",  new Integer(35)},
                {"Beefeater BurroughsBeefeater Burroughs Reserve",  new Integer(24)},
                {"Beefeater Crown Jewel",  new Integer(16)},
                {"Beefeater Pink",  new Integer(35)},
                {"Bulldog",  new Integer(24)},
                {"Finsbury",  new Integer(56)},
                {"Finsbury Platinum",  new Integer(48)},
                {"G’ Vine",  new Integer(15)},
                {"Monkey 47",  new Integer(24)},
                {"No3",  new Integer(46)},
                {"Plymouth Gin",  new Integer(25)},
                {"Tanqueray",  new Integer(37)},
                {"Tanqueray Rangpur Dry Gin",  new Integer(32)}
            },
            new String [] {
                "Τζίν", "Διαθεσιμότητα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 307, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Τζίν", jPanel3);

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));

        jTable3.setBackground(new java.awt.Color(102, 0, 0));
        jTable3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable3.setForeground(new java.awt.Color(225, 225, 225));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Havana Club 3",  new Integer(35)},
                {"Havana Club 7",  new Integer(24)},
                {"Havana Club Selección De Maestros",  new Integer(29)},
                {"Havana Club Union",  new Integer(36)},
                {"Mount Gay 1703",  new Integer(19)},
                {"Mount Gay Black Barrel",  new Integer(38)},
                {"Mount Gay Eclipse",  new Integer(25)},
                {"Mount Gay Extra Old",  new Integer(16)},
                {"The Pink Pigeon",  new Integer(32)},
                {"Varadero 15 ετών",  new Integer(28)},
                {"Varadero Silver Dry",  new Integer(14)}
            },
            new String [] {
                "Ρούμι", "Διαθεσιμότητα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 339, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Ρούμι", jPanel4);

        jPanel5.setBackground(new java.awt.Color(102, 0, 0));

        jTable4.setBackground(new java.awt.Color(102, 0, 0));
        jTable4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable4.setForeground(new java.awt.Color(225, 225, 225));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Don Julio 1942",  new Integer(25)},
                {"Don Julio Anejo",  new Integer(34)},
                {"Don Julio Blanco",  new Integer(29)},
                {"Don Julio Reposado",  new Integer(36)},
                {"Olmeca Blanco",  new Integer(38)},
                {"Olmeca Reposado",  new Integer(28)}
            },
            new String [] {
                "Τεκίλα", "Διαθεσιμότητα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 419, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Τεκίλα", jPanel5);

        jPanel6.setBackground(new java.awt.Color(102, 0, 0));

        jTable5.setBackground(new java.awt.Color(102, 0, 0));
        jTable5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable5.setForeground(new java.awt.Color(225, 225, 225));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Aberlour 12 Double Cask",  new Integer(34)},
                {"Aberlour Abunadh",  new Integer(26)},
                {"Ballantines",  new Integer(34)},
                {"Ballantines 12",  new Integer(35)},
                {"Chivas Regal 12",  new Integer(24)},
                {"Chivas Regal 18",  new Integer(37)},
                {"Chivas Regal 25",  new Integer(19)},
                {"Chivas Regal Extra",  new Integer(35)},
                {"Chivas Regal The Icon",  new Integer(26)},
                {"Glenlivet 15",  new Integer(52)},
                {"Glenlivet 18",  new Integer(34)},
                {"Glenlivet 21",  new Integer(24)},
                {"Glenlivet Founders Reserve",  new Integer(39)},
                {"Jameson Caskmates",  new Integer(37)},
                {"Scapa Glansa",  new Integer(34)},
                {"Scapa Skiren",  new Integer(24)},
                {"Redbreast 12",  new Integer(29)}
            },
            new String [] {
                "Ουίσκι", "Διαθεσιμότητα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 243, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Ουίσκι", jPanel6);

        jPanel7.setBackground(new java.awt.Color(102, 0, 0));

        jTable6.setBackground(new java.awt.Color(102, 0, 0));
        jTable6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable6.setForeground(new java.awt.Color(225, 225, 225));
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ΑΚΑΚΙΕΣ AΦΡΩΔΕΣ ΚΥΡ ΓΙΑΝΝΗ Έτος:2014",  new Integer(24)},
                {"ΑΚΑΚΙΕΣ ΚΥΡ ΓΙΑΝΝΗ Ετος 2015 Ποικιλιακή",  new Integer(16)},
                {"ΔΙΑΠΟΡΟΣ ΚΥΡ ΓΙΑΝΝΗ Έτος:2012",  new Integer(25)},
                {"ΔΥΟ ΕΛΙΕΣ ΚΥΡ ΓΙΑΝΝΗ Έτος :2012",  new Integer(16)},
                {"ΚΑΛΗ ΡΙΖΑ ΚΥΡ ΓΙΑΝΝΗ Ετος:2013",  new Integer(54)},
                {"Κτήμα Κυρ-Γιάννη Έτος :2012 Ποικιλιακή",  new Integer(34)},
                {"ΠΑΡΑΓΚΑ ΕΡΥΘΡΟΣ ΚΥΡ ΓΙΑΝΝΗ Ετος:2014",  new Integer(36)},
                {"Παράγκα λευκή Αφρώδης Έτος:2014",  new Integer(16)},
                {"ΠΑΡΑΓΚΑ ΛΕΥΚΟΣ ΚΥΡ ΓΙΑΝΝΗ Έτος :2015",  new Integer(35)},
                {"Παράγκα ροζέ Έτος:2014 ",  new Integer(28)},
                {"ΡΑΜΝΙΣΤΑ ΚΥΡ ΓΙΑΝΝΗ Έτος :2012",  new Integer(37)},
                {"ΣΑΜΑΡΟΠΕΤΡΑ ΚΥΡ ΓΙΑΝΝΗ",  new Integer(46)},
                {"ΤΕΣΣΕΡΙΣ ΛΙΜΝΕΣ ΚΥΡ ΓΙΑΝΝΗ Έτος:2015",  new Integer(19)},
                {"Τέχνη Αλυπίας Μαλαγουζιά Έτος :2016",  new Integer(38)}
            },
            new String [] {
                "Κρασί", "Διαθεσιμότητα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 291, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Κρασί", jPanel7);

        jPanel8.setBackground(new java.awt.Color(102, 0, 0));

        jTable7.setBackground(new java.awt.Color(102, 0, 0));
        jTable7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable7.setForeground(new java.awt.Color(225, 225, 225));
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Καζανιστό Στουπάκη",  new Integer(24)},
                {"Ούζο 12",  new Integer(53)},
                {"Πιτσιλαδή",  new Integer(13)},
                {"Τσιλιλή Με Γλυκάνισο",  new Integer(34)},
                {"Τσιλιλή Με Γλυκάνισο",  new Integer(14)}
            },
            new String [] {
                "Αποστάγματα", "Διαθεσιμότητα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 435, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Αποστάγματα", jPanel8);

        jPanel9.setBackground(new java.awt.Color(102, 0, 0));

        jTable8.setBackground(new java.awt.Color(102, 0, 0));
        jTable8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable8.setForeground(new java.awt.Color(225, 225, 225));
        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Fee Brothers Cherry Bitters",  new Integer(35)},
                {"Fee Brothers Orange Bitters",  new Integer(24)},
                {"Fee Brothers Black Walnut Bitters",  new Integer(57)},
                {"Fee Brothers Cardamon Bitters",  new Integer(23)},
                {"Fee Brothers Celery Bitters",  new Integer(54)},
                {"Fee Brothers Aztec Chocolate Bitters",  new Integer(29)},
                {"Fee Brothers Cranberry Bitters",  new Integer(35)},
                {"Fee Brothers Gin Barrel Aged Bitters",  new Integer(25)},
                {"Fee Brothers Grapefruit Bitters",  new Integer(27)}
            },
            new String [] {
                "Κοκτέιλ", "Διαθεσιμότητα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 371, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Κοκτέιλ", jPanel9);

        jPanel10.setBackground(new java.awt.Color(102, 0, 0));

        jTable9.setBackground(new java.awt.Color(102, 0, 0));
        jTable9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable9.setForeground(new java.awt.Color(225, 225, 225));
        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Fix Hellas 500ml",  new Integer(24)},
                {"Fix Hellas 330ml",  new Integer(36)},
                {"Heineken 500ml",  new Integer(18)},
                {"Henniger 500ml",  new Integer(19)},
                {"Mythos 500ml",  new Integer(40)},
                {"Sol 300ml",  new Integer(38)},
                {"Νήσος Βιολογική All-Day 330ml",  new Integer(45)},
                {"Amstel 500ml",  new Integer(36)},
                {"Corona Extra 355ml",  new Integer(25)},
                {"Άλφα 500ml",  new Integer(37)},
                {"Kaiser 500ml",  new Integer(31)},
                {"Amstel Radler 500ml",  new Integer(24)}
            },
            new String [] {
                "Μπύρες", "Διαθεσιμότητα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(jTable9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 323, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Μπύρες", jPanel10);

        jPanel11.setBackground(new java.awt.Color(102, 0, 0));

        jTable10.setBackground(new java.awt.Color(102, 0, 0));
        jTable10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable10.setForeground(new java.awt.Color(225, 225, 225));
        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Laurent-Perrier Brut", null},
                {"Laurent-Perrier Demi-Sec", null},
                {"Laurent-Perrier Roze Brut", null}
            },
            new String [] {
                "Σαμπάνιες", "Τιμές"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane10.setViewportView(jTable10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 467, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Σαμπάνιες", jPanel11);

        jPanel12.setBackground(new java.awt.Color(102, 0, 0));

        jTable11.setBackground(new java.awt.Color(102, 0, 0));
        jTable11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable11.setForeground(new java.awt.Color(225, 225, 225));
        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Amaretto Gogio",  new Integer(36)},
                {"Batida De Coco",  new Integer(48)},
                {"Cherry Heering",  new Integer(34)},
                {"Cointreau",  new Integer(31)},
                {"Galliano L' Autentico",  new Integer(26)},
                {"Kahlua",  new Integer(31)},
                {"Malibu",  new Integer(31)},
                {"Ομηρικό",  new Integer(49)},
                {"Pisang Ambon",  new Integer(37)},
                {"Southern Comfort lime",  new Integer(26)}
            },
            new String [] {
                "Λικέρ", "Απόθεμα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane11.setViewportView(jTable11);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 355, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Λικέρ", jPanel12);

        jPanel13.setBackground(new java.awt.Color(102, 0, 0));

        jTable12.setBackground(new java.awt.Color(102, 0, 0));
        jTable12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable12.setForeground(new java.awt.Color(225, 225, 225));
        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Arizona peach",  new Integer(26)},
                {"Arizona Pomegranate",  new Integer(48)},
                {"Nestea Πράσινο Τσάι Λεμόνι Sugar Free",  new Integer(64)}
            },
            new String [] {
                "Ροφήματα", "Απόθεμα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane12.setViewportView(jTable12);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 467, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Ροφήματα", jPanel13);

        jPanel14.setBackground(new java.awt.Color(102, 0, 0));

        jTable13.setBackground(new java.awt.Color(102, 0, 0));
        jTable13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable13.setForeground(new java.awt.Color(225, 225, 225));
        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"'Eψα Πορτοκαλάδα Χωρίς Ανθρακικό 330ml",  new Integer(36)},
                {"Coca Cola Cherry Κουτί 330ml",  new Integer(26)},
                {"Coca Cola Light PET 1.5Lt",  new Integer(18)},
                {"Coca Cola PET 1.5Lt",  new Integer(34)},
                {"Coca Cola Vanilla 330ml",  new Integer(27)},
                {"Coca Cola Zero Lemon Κουτί 330ml",  new Integer(46)},
                {"Coca Cola Zero PET 1.5Lt",  new Integer(18)},
                {"Fanta Λεμονάδα PET 1.5Lt",  new Integer(37)},
                {"Fanta Πορτοκαλάδα Με Ανθρακικό PET 1.5Lt",  new Integer(25)},
                {"Fanta Πορτοκαλάδα Με Ανθρακικό PET 500ml",  new Integer(18)},
                {"Fanta Λεμονάδα PET 500ml",  new Integer(36)},
                {"Fanta Φράουλα PET 500ml",  new Integer(34)},
                {"Schweppes Indian Tonic PET 500ml",  new Integer(29)},
                {"Schweppes Soda PET 500ml",  new Integer(24)},
                {"Sprite PET 500ml",  new Integer(15)},
                {"Έψα Λεμονάδα 330ml",  new Integer(16)},
                {"Έψα Πορτοκαλάδα Με Ανθρακικό 330ml",  new Integer(34)}
            },
            new String [] {
                "Αναψυκτικά", "Απόθεμα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane13.setViewportView(jTable13);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 243, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Αναψυκτικά", jPanel14);

        jPanel15.setBackground(new java.awt.Color(102, 0, 0));

        jTable14.setBackground(new java.awt.Color(102, 0, 0));
        jTable14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable14.setForeground(new java.awt.Color(225, 225, 225));
        jTable14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Martell Cognac XO",  new Integer(34)},
                {"METAXA Honey",  new Integer(26)},
                {"Metaxa Private Reserve",  new Integer(49)},
                {"Remy Martin VSOP Mature Cask Finish",  new Integer(24)},
                {"Remy Martin XO Excellence",  new Integer(19)},
                {"ΜΕΤΑΧΑ 12 ΑΣΤΕΡΩΝ",  new Integer(38)},
                {"ΜΕΤΑΧΑ 5 ΑΣΤΕΡΩΝ",  new Integer(27)},
                {"ΜΕΤΑΧΑ 7 ΑΣΤΕΡΩΝ",  new Integer(39)}
            },
            new String [] {
                "Κονιάκ", "Απόθεμα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane14.setViewportView(jTable14);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 386, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Κονιάκ", jPanel15);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(225, 225, 225));
        jButton1.setText("Πίσω");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(225, 225, 225));
        jButton3.setText("Νέα Προμήθεια");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(0, 123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
menu menu= new menu();
menu.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
promithia promithia=new promithia();
promithia.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diathesimotita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diathesimotita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diathesimotita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diathesimotita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diathesimotita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable13;
    private javax.swing.JTable jTable14;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    // End of variables declaration//GEN-END:variables
}
